spring.application.name=borrower-service

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/loanapplication_db
spring.datasource.username=postgres
<<<<<<< HEAD
spring.datasource.password=raju
=======
spring.datasource.password=sujeeth@1503
>>>>>>> f58e01cd013fb1db0718eba62329d9efbff2c8c9

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect